In [81]:
import numpy as np
#untuk membaca citra
import cv2 as cv  
#fungsi operasi matematika.
import math  
#untuk olah dan analisis data
import pandas as pd  

In [82]:
glcm = pd.read_csv('C:/Users/bona/new_glcm_4c.csv',delimiter=',')

In [83]:
glcm.head()

Unnamed: 0  contrast_0  contrast_45  contrast_90  contrast_135  \
0           0   37.014785   158.638462   124.498413    132.124176   
1           1   59.260666   262.956758   207.001916    215.818407   
2           2   56.768194   262.523956   213.265900    229.534396   
3           3   56.196508   184.761209   146.519869    175.395000   
4           4   60.556574   251.444396   203.540394    223.631813   

   dissimilarity_0  dissimilarity_45  dissimilarity_90  dissimilarity_135  \
0         1.747791          3.203297          2.745758           3.116044   
1         2.187016          4.111484          3.477230           3.824451   
2         2.200655          4.365879          3.770662           4.179835   
3         2.063939          3.539176          3.028407           3.528077   
4         2.415876          4.427088          3.813027           4.320549   

   homogeneity_0  ...  homogeneity_135     ASM_0    ASM_45    ASM_90  \
0       0.772832  ...         0.757693  0.480397  0.474112  0.477799   
1       0.771249  ...         0.759221  0.492941  0.485945  0.489058   
2       0.735245  ...         0.712588  0.408166  0.400254  0.403095   
3       0.752072  ...         0.736044  0.439005  0.431831  0.434660   
4       0.726729  ...         0.707924  0.399465  0.391956  0.395065   

    ASM_135  energy_0  energy_45  energy_90  energy_135  label  
0  0.474195  0.693107   0.688558   0.691230    0.688618      0  
1  0.485997  0.702098   0.697098   0.699327    0.697135      0  
2  0.400943  0.638878   0.632656   0.634898    0.633200      0  
3  0.431902  0.662574   0.657139   0.659288    0.657193      0  
4  0.391865  0.632033   0.626064   0.628542    0.625991      0  

[5 rows x 22 columns]

In [84]:
# glcm.columns = ['contrast_0', 'contrast_45', 'contrast_90', 'contrast_135', 'dissimilarity_0', 'dissimilarity_45', 'dissimilarity_90', 'dissimilarity_135', 'homogeneity_0', 'homogeneity_45', 'homogeneity_90', 'homogeneity_135', 'ASM_0', 'ASM_45', 'ASM_90', 'ASM_135', 'energy_0', 'energy_45', 'energy_90', 'energy_135', 'correlation_0', 'correlation_45', 'correlation_90', 'correlation_135', 'label']

In [85]:
## COBA KNN
# ACAK DATASET
from sklearn.utils import shuffle

df = shuffle(glcm)
df

Unnamed: 0  contrast_0  contrast_45  contrast_90  contrast_135  \
46          46   23.645772   181.780934   160.315873    164.980165   
57          57   25.068740   160.661209   131.000766    128.064286   
7            7   51.562902   210.557033   169.455610    189.003626   
56          56   18.438843   124.410495   112.088123    118.633187   
42          42   23.651773   140.765275   121.569458    125.041978   
43          43   37.362520   182.013681   156.733005    169.071484   
37          37   34.801037   211.434121   186.620635    194.451813   
41          41   23.989525   166.899945   139.712808    137.478407   
9            9   40.930769   141.636099   118.679967    137.112473   
55          55   23.728860   182.080330   150.971648    145.746429   
45          45   25.867103   140.616593   115.894226    119.129780   
13          13   49.814948   214.724780   172.340120    185.665824   
19          19   51.898527   251.603242   219.122222    239.017692   
26          26   55.092035   297.419835   253.090969    271.698681   
0            0   37.014785   158.638462   124.498413    132.124176   
44          44   17.992744   122.024396   100.697756    100.471538   
35          35   29.550464   181.850495   147.514176    147.096319   
28          28   49.427278   226.689231   189.237001    208.596813   
30          30   29.979214   152.817637   150.564587    183.185495   
18          18   61.617185   251.769011   201.274330    217.151429   
14          14   41.080633   197.258791   162.242091    167.332967   
31          31   29.805565   143.916484   130.882485    150.269451   
20          20   48.515930   191.643571   170.174056    204.154341   
54          54   20.668631   147.807143   136.378161    145.065385   
17          17   60.723732   250.920275   192.683634    201.345934   
4            4   60.556574   251.444396   203.540394    223.631813   
39          39   51.045117   224.319890   182.440339    197.451648   
59          59   27.782870   153.553901   135.198248    146.119670   
15          15   52.308074   213.076044   163.759989    172.889011   
40          40   39.988380   174.439780   155.061631    182.159066   
22          22   36.065466   166.921978   150.901095    178.375055   
12          12   58.965248   225.432473   184.828134    213.236923   
6            6   51.215603   206.370769   166.402956    180.270934   
3            3   56.196508   184.761209   146.519869    175.395000   
58          58   19.866939   135.257967   119.559059    125.091099   
21          21   28.033115   155.596813   143.294964    160.558242   
24          24   33.922040   195.843407   180.076628    202.085714   
10          10   59.080360   239.248901   184.720635    200.863242   
1            1   59.260666   262.956758   207.001916    215.818407   
33          33   28.366994   177.284780   154.860701    166.710055   
50          50   41.912602   238.932253   174.069622    154.932418   
53          53   23.951391   160.123077   137.974822    139.503791   
49          49   24.187998   163.724396   145.293815    152.939835   
8            8   34.941626   133.587198   110.546798    124.555934   
16          16   56.740426   251.842527   201.283415    206.195000   
52          52   27.795526   160.938516   139.344335    149.665110   
29          29   49.281233   255.229011   190.649261    188.518462   
23          23   34.587998   223.851209   198.474165    212.197418   
27          27   59.401637   257.860934   227.776026    265.788077   
36          36   56.128860   253.237637   204.911823    225.343956   
2            2   56.768194   262.523956   213.265900    229.534396   
5            5   49.681178   220.298022   190.852436    215.762747   
47          47   23.334097   159.108297   125.527203    118.611099   
34          34   45.015767   206.396593   190.689436    220.307308   
32          32   26.599509   116.424890   101.359223    120.855549   
38          38   45.313148   217.215330   192.436125    218.381099   
48          48

In [86]:
# #create a dataframe with all training data except the target column
x = df.drop(columns=['label'])

# #check that the target variable has been removed
x.head()

Unnamed: 0  contrast_0  contrast_45  contrast_90  contrast_135  \
46          46   23.645772   181.780934   160.315873    164.980165   
57          57   25.068740   160.661209   131.000766    128.064286   
7            7   51.562902   210.557033   169.455610    189.003626   
56          56   18.438843   124.410495   112.088123    118.633187   
42          42   23.651773   140.765275   121.569458    125.041978   

    dissimilarity_0  dissimilarity_45  dissimilarity_90  dissimilarity_135  \
46         1.092144          2.925934          2.703284           2.796758   
57         1.381997          3.200934          2.759278           2.854066   
7          2.067321          3.843736          3.313136           3.696868   
56         0.961702          2.280879          2.126929           2.226813   
42         1.095090          2.490604          2.244007           2.311758   

    homogeneity_0  ...  homogeneity_90  homogeneity_135     ASM_0    ASM_45  \
46       0.835291  ...        0.821398         0.813519  0.591177  0.583575   
57       0.792952  ...        0.784152         0.772031  0.507749  0.501267   
7        0.767488  ...        0.761985         0.750159  0.479724  0.472169   
56       0.846659  ...        0.835867         0.829356  0.607202  0.601223   
42       0.855173  ...        0.845998         0.840761  0.641129  0.635366   

      ASM_90   ASM_135  energy_0  energy_45  energy_90  energy_135  
46  0.585835  0.583498  0.768880   0.763921   0.765398    0.763870  
57  0.504560  0.502015  0.712565   0.708002   0.710324    0.708530  
7   0.475514  0.472512  0.692621   0.687145   0.689575    0.687395  
56  0.604038  0.601308  0.779232   0.775385   0.777199    0.775441  
42  0.636574  0.635374  0.800705   0.797099   0.797856    0.797103  

[5 rows x 21 columns]

In [87]:
#separate target values
y = df['label'].values

#view target values
y

array([2, 2, 0, 2, 2, 2, 1, 2, 0, 2, 2, 0, 0, 1, 0, 2, 1, 1, 1, 0, 0, 1,
       1, 2, 0, 0, 1, 2, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 2, 0,
       0, 2, 1, 1, 1, 1, 0, 0, 2, 1, 1, 1, 2, 2, 1, 0], dtype=int64)

In [88]:
type(x)

pandas.core.frame.DataFrame

In [89]:
x = x.to_numpy()

In [90]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.metrics import confusion_matrix
from statistics import mean 

labels = [0,1,2]
acc=[]
presisi=[]
recal=[]

tprs = []

fold = 1

skfold = StratifiedKFold(n_splits=5, shuffle = True)

for i, (train, test) in enumerate(skfold.split(x, y), start=1):
    print('fold : ', i)
    x_train, x_test = x[train], x[test]
    y_train, y_test = y[train], y[test]
    # Create KNN classifier
    knn = KNeighborsClassifier(n_neighbors = 7)

    # Fit the classifier to the data
    knn.fit(x_train,y_train)
    
    result = knn.predict(x_test)
    
    print(y_test)
    print(result)

    cf_klasifikasi = pd.DataFrame(data=confusion_matrix(y_test, result, labels=labels), columns=labels, index=labels)
    print(cf_klasifikasi)
    
    tps_klasifikasi = {}
    fps_klasifikasi  = {}
    fns_klasifikasi  = {}
    tns_klasifikasi  = {}
    for label in labels:
        tps_klasifikasi[label] = cf_klasifikasi.loc[label, label]
        fps_klasifikasi[label] = cf_klasifikasi[label].sum() - tps_klasifikasi[label]
        fns_klasifikasi[label] = cf_klasifikasi.loc[label].sum() - tps_klasifikasi[label]

    for label in set(y_test):
        tns_klasifikasi[label] = len(y_test) - (tps_klasifikasi[label] + fps_klasifikasi[label] + fns_klasifikasi[label])

    accuracy_global_new_klasifikasi=sum(tps_klasifikasi.values())/len(y_test)
    acc.append(accuracy_global_new_klasifikasi)


    tpfp_klasifikasi = [ai + bi for ai, bi in zip(list(tps_klasifikasi.values()), list(fps_klasifikasi.values()))]
    precision=[ai / bi if bi>0 else 0 for ai , bi in zip(list(tps_klasifikasi.values()), tpfp_klasifikasi)]
    precisionklasifikasi=sum(precision)/3
    presisi.append(precisionklasifikasi)

    tpfn_klasifikasi = [ai + bi for ai, bi in zip(list(tps_klasifikasi.values()), list(fns_klasifikasi.values()))]
    recall=[ai / bi if bi>0 else 0 for ai, bi in zip(list(tps_klasifikasi.values()), tpfn_klasifikasi)]
    recallklasifikasi=sum(recall)/3
    recal.append(recallklasifikasi)

    print('akurasi : ',accuracy_global_new_klasifikasi)
    print('presisi : ',precisionklasifikasi)
    print('recall : ',recallklasifikasi,'\n')
print('###############################################\n')    
print('rata2 akurasi : ', mean(acc))
print('rata2 presisi : ', mean(presisi))
print('rata2 recal : ', mean(recal))

fold :  1
[2 2 2 0 1 0 2 0 0 1 1 1]
[2 2 2 0 1 0 2 0 0 2 1 1]
   0  1  2
0  4  0  0
1  0  3  1
2  0  0  4
akurasi :  0.9166666666666666
presisi :  0.9333333333333332
recall :  0.9166666666666666 

fold :  2
[2 0 2 0 0 1 1 0 2 1 1 2]
[2 0 2 0 0 0 1 0 2 0 0 2]
   0  1  2
0  4  0  0
1  3  1  0
2  0  0  4
akurasi :  0.75
presisi :  0.8571428571428571
recall :  0.75 

fold :  3
[2 1 0 1 1 0 2 2 0 0 1 2]
[2 0 0 2 1 0 0 2 0 0 1 1]
   0  1  2
0  4  0  0
1  1  2  1
2  1  1  2
akurasi :  0.6666666666666666
presisi :  0.6666666666666666
recall :  0.6666666666666666 

fold :  4
[0 2 2 1 0 2 0 1 1 0 2 1]
[0 2 2 2 0 1 0 1 1 0 2 1]
   0  1  2
0  4  0  0
1  0  3  1
2  0  1  3
akurasi :  0.8333333333333334
presisi :  0.8333333333333334
recall :  0.8333333333333334 

fold :  5
[2 1 0 2 1 0 2 0 2 1 1 0]
[2 1 0 2 1 0 2 2 2 1 2 1]
   0  1  2
0  2  1  1
1  0  3  1
2  0  0  4
akurasi :  0.75
presisi :  0.8055555555555555
recall :  0.75 

###############################################

rata2 akurasi :  0.783